target 'cenacle' do
    platform :ios, '9.0'
    
    # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'GooglePlacePicker', '= 2.0.1'
    pod 'GooglePlaces', '= 2.0.1'
    pod 'GoogleMaps', '= 2.0.1'
    


end