target 'cenacle' do
    platform :ios, '9.0'
    
    # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'GooglePlacePicker'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    


end